defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  8d897e72-789e-48bd-b2c5-05e3dde851a7: # Council Of Entrepreneurs 
    enabledByDefault: true
    hasUrls: true
    template: pages\about\index.twig
    uriFormat: about
type: single
