columnSuffix: null
contentColumnType: string
fieldGroup: 343c118a-3a3b-450d-bad7-d715943511f0 # Common
handle: componentMatrix
instructions: null
name: 'Component Matrix'
searchable: false
settings:
  contentTable: '{{%matrixcontent_componentmatrix}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
