columnSuffix: null
contentColumnType: string
fieldGroup: 343c118a-3a3b-450d-bad7-d715943511f0 # Common
handle: industryPicker
instructions: null
name: 'Industry Picker'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:e263b920-aa56-4377-aeb4-2a98b3e14294' # Member Industry
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
