columnSuffix: noeesvjs
contentColumnType: boolean
fieldGroup: 343c118a-3a3b-450d-bad7-d715943511f0 # Common
handle: lightswitch01
instructions: null
name: Lightswitch01
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
