columnSuffix: null
contentColumnType: string
fieldGroup: 343c118a-3a3b-450d-bad7-d715943511f0 # Common
handle: stagePicker
instructions: null
name: 'Stage Picker'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:51899720-4683-47e5-988f-e6bce13b5235' # Member Stage
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
