field: fd6312bb-8493-408e-86e7-900dda8fcd3e # Component Matrix
fieldLayouts:
  286f9690-ba75-493b-97ba-baef4ca94016:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 63e58ee9-667e-47ab-8d86-b93f7cb6dad8 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78008350-dc46-4630-b448-afb751204cf7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06fc47ff-0df5-4105-ae6d-a490159ff8c7 # Section Handle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0c9eda1-339e-4faa-a5f0-1a7383636c4e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90539499-c14c-4a81-a677-5b8b3e81f9fa
        userCondition: null
fields:
  06fc47ff-0df5-4105-ae6d-a490159ff8c7: # Section Handle
    columnSuffix: vrckjrzm
    contentColumnType: text
    fieldGroup: null
    handle: sectionHandle
    instructions: null
    name: 'Section Handle'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  63e58ee9-667e-47ab-8d86-b93f7cb6dad8: # Background Color
    columnSuffix: fsgrchha
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Yellow
            -
              - value
              - yellow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Brick
            -
              - value
              - brick
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Light Blue'
            -
              - value
              - blue-light
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - navy
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Salmon
            -
              - value
              - salmon
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Slate
            -
              - value
              - slate
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Brown
            -
              - value
              - brown
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: featuredPost
name: 'Featured Post'
sortOrder: 8
