field: fd6312bb-8493-408e-86e7-900dda8fcd3e # Component Matrix
fieldLayouts:
  b76f2294-7203-4da1-8bd9-af0bba757f2e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 97d24863-0a77-4cc9-ad82-f4aae29a8627 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dddeeb87-cd65-4b08-9941-e3fa46b525cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d59d3a6-bfe2-487d-aa0d-da1db81aaf5c # Column One Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0922ae5-554a-44ff-82a4-997f86a8e57c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: edc670e8-2842-4545-a731-f01d67817b72 # Form Handle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbf1acf6-0db0-46f1-adce-6bd6edf5fb41
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44225ebb-045f-464a-b7ed-97ce27152e15
        userCondition: null
fields:
  7d59d3a6-bfe2-487d-aa0d-da1db81aaf5c: # Column One Content
    columnSuffix: zwcciwyj
    contentColumnType: text
    fieldGroup: null
    handle: columnOneContent
    instructions: null
    name: 'Column One Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  97d24863-0a77-4cc9-ad82-f4aae29a8627: # Background Color
    columnSuffix: vnrajkty
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Yellow
            -
              - value
              - yellow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Brick
            -
              - value
              - brick
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Light Blue'
            -
              - value
              - lightBlue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - navy
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Salmon
            -
              - value
              - salmon
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Slate
            -
              - value
              - slate
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Brown
            -
              - value
              - brown
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  edc670e8-2842-4545-a731-f01d67817b72: # Form Handle
    columnSuffix: pjxujnmn
    contentColumnType: text
    fieldGroup: null
    handle: formHandle
    instructions: null
    name: 'Form Handle'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: twoColumnForm
name: 'Two Column Form'
sortOrder: 9
